=begin
#BillForward REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Bfwd::FixedtermsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FixedtermsApi' do
  before do
    # run before each test
    @instance = Bfwd::FixedtermsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FixedtermsApi' do
    it 'should create an instance of FixedtermsApi' do
      expect(@instance).to be_instance_of(Bfwd::FixedtermsApi)
    end
  end

  # unit tests for update_fixed_term
  # Update
  # {\&quot;nickname\&quot;:\&quot;Update a fixed term\&quot;,\&quot;request\&quot;:\&quot;updateFixedTermRequest.html\&quot;,\&quot;response\&quot;:\&quot;updateFixedTermResponse.html\&quot;}
  # @param payment_method The payment-method object to be updated.
  # @param [Hash] opts the optional parameters
  # @return [FixedTermPagedMetadata]
  describe 'update_fixed_term test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
