=begin
#BillForward REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Bfwd::PricingcomponentvaluechangesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PricingcomponentvaluechangesApi' do
  before do
    # run before each test
    @instance = Bfwd::PricingcomponentvaluechangesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PricingcomponentvaluechangesApi' do
    it 'should create an instance of PricingcomponentvaluechangesApi' do
      expect(@instance).to be_instance_of(Bfwd::PricingcomponentvaluechangesApi)
    end
  end

  # unit tests for create_pricing_component_value_change
  # Create a pricing-component-value-change.
  # {\&quot;nickname\&quot;:\&quot;Create\&quot;,\&quot;request\&quot;:\&quot;createPricingComponentValueChangeRequest.html\&quot;,\&quot;response\&quot;:\&quot;createPricingComponentValueChangeResponse.html\&quot;}
  # @param pricing_component_value_change The pricing-component-value-change object to be updated.
  # @param [Hash] opts the optional parameters
  # @return [PricingComponentValueChangePagedMetadata]
  describe 'create_pricing_component_value_change test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_all_pricing_component_value_changes
  # Returns a collection of pricing-component-value-changes. By default 10 values are returned. Records are returned in natural order.
  # {\&quot;nickname\&quot;:\&quot;Get All\&quot;,\&quot;response\&quot;:\&quot;getPricingComponentValueChangeAll.html\&quot;}
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :organizations A list of organization-IDs used to restrict the scope of API calls.
  # @option opts [Integer] :offset The offset from the first pricing-component-value-change to return.
  # @option opts [Integer] :records The maximum number of pricing-component-value-changes to return.
  # @option opts [String] :order_by Specify a field used to order the result set.
  # @option opts [String] :order Ihe direction of any ordering, either ASC or DESC.
  # @return [PricingComponentValueChangePagedMetadata]
  describe 'get_all_pricing_component_value_changes test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_pricing_component_value_change
  # Returns a single pricing-component-value-changes, specified by the ID parameter.
  # {\&quot;nickname\&quot;:\&quot;Retrieve by id\&quot;,\&quot;response\&quot;:\&quot;getPricingComponentValueChangeByID.html\&quot;}
  # @param id The string ID of the pricing-component-value-change.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :organizations A list of organization-IDs used to restrict the scope of API calls.
  # @return [PricingComponentValueChangePagedMetadata]
  describe 'get_pricing_component_value_change test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_pricing_component_value_change_by_component_id
  # Returns a collection of pricing-component-value-changes, specified by the pricing-component-value-ID parameter. By default 10 values are returned. Records are returned in natural order.
  # {\&quot;nickname\&quot;:\&quot;Retrieve by Component-ID\&quot;,\&quot;response\&quot;:\&quot;getPricingComponentValueChangeByID.html\&quot;}
  # @param pricing_component_id The string ID of the pricing-component-value.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :organizations A list of organization-IDs used to restrict the scope of API calls.
  # @option opts [Integer] :offset The offset from the first pricing-component-value-change to return.
  # @option opts [Integer] :records The maximum number of pricing-component-value-changes to return.
  # @option opts [String] :order_by Specify a field used to order the result set.
  # @option opts [String] :order Ihe direction of any ordering, either ASC or DESC.
  # @return [PricingComponentValueChangePagedMetadata]
  describe 'get_pricing_component_value_change_by_component_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_pricing_component_value_change_by_invoice_id
  # Returns a collection of pricing-component-value-changes, specified by the invoice-ID parameter. By default 10 values are returned. Records are returned in natural order.
  # {\&quot;nickname\&quot;:\&quot;Retrieve by Invoice-ID\&quot;,\&quot;response\&quot;:\&quot;getPricingComponentValueChangeByInvoiceID.html\&quot;}
  # @param invoice_id The string invoice-ID of the pricing-component-value-change.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :organizations A list of organization-IDs used to restrict the scope of API calls.
  # @option opts [Integer] :offset The offset from the first pricing-component-value-change to return.
  # @option opts [Integer] :records The maximum number of pricing-component-value-changes to return.
  # @option opts [String] :order_by Specify a field used to order the result set.
  # @option opts [String] :order Ihe direction of any ordering, either ASC or DESC.
  # @return [PricingComponentValueChangePagedMetadata]
  describe 'get_pricing_component_value_change_by_invoice_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_pricing_component_value_change_by_subscription_id
  # Returns a collection of pricing-component-value-changes, specified by the subscription-ID parameter. By default 10 values are returned. Records are returned in natural order.
  # {\&quot;nickname\&quot;:\&quot;Retrieve by Subscription-ID\&quot;,\&quot;response\&quot;:\&quot;getPricingComponentValueChangeBySubscriptionID.html\&quot;}
  # @param subscription_id ID of the subscription.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :organizations A list of organization-IDs used to restrict the scope of API calls.
  # @option opts [Integer] :offset The offset from the first pricing-component-value-change to return.
  # @option opts [Integer] :records The maximum number of pricing-component-value-changes to return.
  # @option opts [String] :order_by Specify a field used to order the result set.
  # @option opts [String] :order Ihe direction of any ordering, either ASC or DESC.
  # @return [PricingComponentValueChangePagedMetadata]
  describe 'get_pricing_component_value_change_by_subscription_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
