=begin
#BillForward REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require "uri"

module BillForward
  class UsernamesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Create a username.
    # {\"nickname\":\"Create\",\"request\":\"createUsernameRequest.html\",\"response\":\"createUsernameResponse.html\"}
    # @param username The username object to be created.
    # @param [Hash] opts the optional parameters
    # @return [UsernamePagedMetadata]
    def create_username(username, opts = {})
      data, _status_code, _headers = create_username_with_http_info(username, opts)
      return data
    end

    # Create a username.
    # {\&quot;nickname\&quot;:\&quot;Create\&quot;,\&quot;request\&quot;:\&quot;createUsernameRequest.html\&quot;,\&quot;response\&quot;:\&quot;createUsernameResponse.html\&quot;}
    # @param username The username object to be created.
    # @param [Hash] opts the optional parameters
    # @return [Array<(UsernamePagedMetadata, Fixnum, Hash)>] UsernamePagedMetadata data, response status code and response headers
    def create_username_with_http_info(username, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: UsernamesApi.create_username ..."
      end
      # verify the required parameter 'username' is set
      fail ArgumentError, "Missing the required parameter 'username' when calling UsernamesApi.create_username" if username.nil?
      # resource path
      local_var_path = "/usernames".sub('{format}','json')

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['text/xml', 'application/xml', 'application/json']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(username)
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'UsernamePagedMetadata')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: UsernamesApi#create_username\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
